/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign In */
        post: operations["sign_in_api_v1_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session Info */
        get: operations["session_info_api_v1_sessions_current_get"];
        put?: never;
        post?: never;
        /** Sign Out */
        delete: operations["sign_out_api_v1_sessions_current_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Accounts */
        get: operations["list_accounts_api_v1_accounts_get"];
        put?: never;
        /** Create Account */
        post: operations["create_account_api_v1_accounts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{account_id}/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Account Balance */
        get: operations["account_balance_api_v1_accounts__account_id__balance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{account_id}/cash-flows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cash History */
        get: operations["cash_history_api_v1_accounts__account_id__cash_flows_get"];
        put?: never;
        /** Cash Flow */
        post: operations["cash_flow_api_v1_accounts__account_id__cash_flows_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{account_id}/executions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Execution History */
        get: operations["execution_history_api_v1_accounts__account_id__executions_get"];
        put?: never;
        /** Record Execution */
        post: operations["record_execution_api_v1_accounts__account_id__executions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{account_id}/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Positions */
        get: operations["positions_api_v1_accounts__account_id__positions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{account_id}/reconciliation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reconcile */
        get: operations["reconcile_api_v1_accounts__account_id__reconciliation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instruments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Instruments */
        get: operations["list_instruments_api_v1_instruments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instruments/{instrument_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Instrument */
        get: operations["get_instrument_api_v1_instruments__instrument_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instruments/{instrument_id}/quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Quote */
        get: operations["get_quote_api_v1_instruments__instrument_id__quotes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Watches */
        get: operations["get_watches_api_v1_watchlists_get"];
        put?: never;
        /** Add Watch */
        post: operations["add_watch_api_v1_watchlists_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlists/{instrument_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Watch */
        delete: operations["remove_watch_api_v1_watchlists__instrument_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research-capability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Research Capability */
        get: operations["research_capability_api_v1_research_capability_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Evidence */
        post: operations["create_evidence_api_v1_evidence_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evidence/{evidence_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evidence */
        get: operations["get_evidence_api_v1_evidence__evidence_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instruments/{instrument_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Evidence */
        get: operations["list_evidence_api_v1_instruments__instrument_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instruments/{instrument_id}/research": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Research */
        get: operations["list_research_api_v1_instruments__instrument_id__research_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Research Run */
        post: operations["research_run_api_v1_research_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/cancellations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Job */
        post: operations["cancel_job_api_v1_jobs__job_id__cancellations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountBalance */
        AccountBalance: {
            account: components["schemas"]["AccountView"];
            /** Cashbalance */
            cashBalance: string;
        };
        /** AccountInput */
        AccountInput: {
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "REAL" | "SIMULATED";
            /**
             * Currency
             * @default CNY
             * @constant
             */
            currency: "CNY";
            /** Maxpositionpercent */
            maxPositionPercent: number;
        };
        /** AccountPage */
        AccountPage: {
            /** Accounts */
            accounts: components["schemas"]["AccountView"][];
            /** Nextcursor */
            nextCursor: string | null;
        };
        /** AccountView */
        AccountView: {
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "REAL" | "SIMULATED";
            /**
             * Currency
             * @default CNY
             * @constant
             */
            currency: "CNY";
            /** Maxpositionpercent */
            maxPositionPercent: number;
            /** Id */
            id: string;
            /** Version */
            version: number;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /** ActualFees */
        ActualFees: {
            /** Commission */
            commission: string;
            /** Stamptax */
            stampTax: string;
            /** Transferfee */
            transferFee: string;
            /** Otherfee */
            otherFee: string;
            /**
             * Basis
             * @default ACTUAL
             * @constant
             */
            basis: "ACTUAL";
        };
        /** AssessmentOutput */
        AssessmentOutput: {
            /** Summary */
            summary: string;
            /** Claims */
            claims: components["schemas"]["Claim"][];
            /** Counterclaims */
            counterClaims: components["schemas"]["Claim"][];
            /**
             * Thesisstatus
             * @enum {string}
             */
            thesisStatus: "SUPPORTED" | "WEAKENED" | "INVALIDATED" | "UNCERTAIN";
            /** Strategyfit */
            strategyFit: ("TREND" | "VALUE" | "QUALITY" | "EVENT" | "RECOVERY")[];
            /** Uncertainties */
            uncertainties: string[];
            /** Invalidation */
            invalidation: string;
            /** Nextcheck */
            nextCheck: string;
            /**
             * Validuntil
             * Format: date-time
             */
            validUntil: string;
        };
        /** AssessmentPage */
        AssessmentPage: {
            /** Assessments */
            assessments: components["schemas"]["AssessmentView"][];
            /** Nextcursor */
            nextCursor: string | null;
        };
        /** AssessmentView */
        AssessmentView: {
            /** Id */
            id: string;
            /** Jobid */
            jobId: string;
            /** Instrumentid */
            instrumentId: string;
            /** Protocolversion */
            protocolVersion: string;
            /** Modelid */
            modelId: string;
            /**
             * Asof
             * Format: date-time
             */
            asOf: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Inputhash */
            inputHash: string;
            /** Evidenceids */
            evidenceIds: string[];
            output: components["schemas"]["AssessmentOutput"];
            /**
             * Status
             * @default VALIDATED
             * @constant
             */
            status: "VALIDATED";
            /**
             * Usage
             * @default RESEARCH_ONLY
             * @constant
             */
            usage: "RESEARCH_ONLY";
        };
        /** CashEntryView */
        CashEntryView: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "OPENING" | "DEPOSIT" | "WITHDRAWAL" | "EXECUTION";
            /** Amount */
            amount: string;
            /**
             * Effectiveat
             * Format: date-time
             */
            effectiveAt: string;
            /**
             * Recordedat
             * Format: date-time
             */
            recordedAt: string;
            /** Source */
            source: string;
            /** Accountversion */
            accountVersion: number;
            /** Executionid */
            executionId?: string | null;
        };
        /** CashFlowInput */
        CashFlowInput: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "OPENING" | "DEPOSIT" | "WITHDRAWAL";
            /** Amount */
            amount: string;
            /**
             * Effectiveat
             * Format: date-time
             */
            effectiveAt: string;
            /** Source */
            source: string;
            /** Expectedversion */
            expectedVersion: number;
        };
        /** CashPage */
        CashPage: {
            /** Entries */
            entries: components["schemas"]["CashEntryView"][];
            /** Nextcursor */
            nextCursor: string | null;
        };
        /** Claim */
        Claim: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "OBSERVED" | "INFERRED" | "HYPOTHESIS";
            /** Statement */
            statement: string;
            /** Evidenceids */
            evidenceIds: string[];
        };
        /** Discrepancy */
        Discrepancy: {
            /** Reference */
            reference: string;
            /** Field */
            field: string;
            /** Expected */
            expected: string;
            /** Actual */
            actual: string;
        };
        /** Envelope[AccountBalance] */
        Envelope_AccountBalance_: {
            data: components["schemas"]["AccountBalance"];
            meta?: components["schemas"]["Meta"];
        };
        /** Envelope[AccountPage] */
        Envelope_AccountPage_: {
            data: components["schemas"]["AccountPage"];
            meta?: components["schemas"]["Meta"];
        };
        /** Envelope[AccountView] */
        Envelope_AccountView_: {
            data: components["schemas"]["AccountView"];
            meta?: components["schemas"]["Meta"];
        };
        /** Envelope[AssessmentPage] */
        Envelope_AssessmentPage_: {
            data: components["schemas"]["AssessmentPage"];
            meta?: components["schemas"]["Meta"];
        };
        /** Envelope[CashEntryView] */
        Envelope_CashEntryView_: {
            data: components["schemas"]["CashEntryView"];
            meta?: components["schemas"]["Meta"];
        };
        /** Envelope[CashPage] */
        Envelope_CashPage_: {
            data: components["schemas"]["CashPage"];
            meta?: components["schemas"]["Meta"];
        };
        /** Envelope[EvidencePage] */
        Envelope_EvidencePage_: {
            data: components["schemas"]["EvidencePage"];
            meta?: components["schemas"]["Meta"];
        };
        /** Envelope[EvidenceView] */
        Envelope_EvidenceView_: {
            data: components["schemas"]["EvidenceView"];
            meta?: components["schemas"]["Meta"];
        };
        /** Envelope[ExecutionPage] */
        Envelope_ExecutionPage_: {
            data: components["schemas"]["ExecutionPage"];
            meta?: components["schemas"]["Meta"];
        };
        /** Envelope[ExecutionView] */
        Envelope_ExecutionView_: {
            data: components["schemas"]["ExecutionView"];
            meta?: components["schemas"]["Meta"];
        };
        /** Envelope[Health] */
        Envelope_Health_: {
            data: components["schemas"]["Health"];
            meta?: components["schemas"]["Meta"];
        };
        /** Envelope[InstrumentPage] */
        Envelope_InstrumentPage_: {
            data: components["schemas"]["InstrumentPage"];
            meta?: components["schemas"]["Meta"];
        };
        /** Envelope[InstrumentView] */
        Envelope_InstrumentView_: {
            data: components["schemas"]["InstrumentView"];
            meta?: components["schemas"]["Meta"];
        };
        /** Envelope[JobView] */
        Envelope_JobView_: {
            data: components["schemas"]["JobView"];
            meta?: components["schemas"]["Meta"];
        };
        /** Envelope[PositionPage] */
        Envelope_PositionPage_: {
            data: components["schemas"]["PositionPage"];
            meta?: components["schemas"]["Meta"];
        };
        /** Envelope[QuoteView] */
        Envelope_QuoteView_: {
            data: components["schemas"]["QuoteView"];
            meta?: components["schemas"]["Meta"];
        };
        /** Envelope[ReconciliationView] */
        Envelope_ReconciliationView_: {
            data: components["schemas"]["ReconciliationView"];
            meta?: components["schemas"]["Meta"];
        };
        /** Envelope[ResearchCapability] */
        Envelope_ResearchCapability_: {
            data: components["schemas"]["ResearchCapability"];
            meta?: components["schemas"]["Meta"];
        };
        /** Envelope[UserView] */
        Envelope_UserView_: {
            data: components["schemas"]["UserView"];
            meta?: components["schemas"]["Meta"];
        };
        /** Envelope[WatchPage] */
        Envelope_WatchPage_: {
            data: components["schemas"]["WatchPage"];
            meta?: components["schemas"]["Meta"];
        };
        /** EvidenceInput */
        EvidenceInput: {
            /** Instrumentid */
            instrumentId: string;
            /** Title */
            title: string;
            /**
             * Sourceurl
             * Format: uri
             */
            sourceUrl: string;
            /**
             * Publishedat
             * Format: date-time
             */
            publishedAt: string;
            /** Text */
            text: string;
            /** Quote */
            quote: string;
        };
        /** EvidencePage */
        EvidencePage: {
            /** Evidence */
            evidence: components["schemas"]["EvidenceView"][];
            /** Nextcursor */
            nextCursor: string | null;
        };
        /** EvidenceView */
        EvidenceView: {
            /** Instrumentid */
            instrumentId: string;
            /** Title */
            title: string;
            /**
             * Sourceurl
             * Format: uri
             */
            sourceUrl: string;
            /**
             * Publishedat
             * Format: date-time
             */
            publishedAt: string;
            /** Text */
            text: string;
            /** Quote */
            quote: string;
            /** Id */
            id: string;
            /** Contenthash */
            contentHash: string;
            /**
             * Firstseenat
             * Format: date-time
             */
            firstSeenAt: string;
            /**
             * Availableat
             * Format: date-time
             */
            availableAt: string;
            /**
             * Provenance
             * @constant
             */
            provenance: "USER_SUPPLIED";
            /**
             * Validation
             * @constant
             */
            validation: "QUOTE_MATCHED";
        };
        /** ExecutionInput */
        ExecutionInput: {
            /** Instrumentid */
            instrumentId: string;
            /** Sourcekey */
            sourceKey: string;
            /**
             * Side
             * @enum {string}
             */
            side: "BUY" | "SELL";
            /** Quantityshares */
            quantityShares: number;
            /** Price */
            price: string;
            /**
             * Executedat
             * Format: date-time
             */
            executedAt: string;
            fees: components["schemas"]["ActualFees"];
            /** Source */
            source: string;
            /** Expectedversion */
            expectedVersion: number;
        };
        /** ExecutionPage */
        ExecutionPage: {
            /** Executions */
            executions: components["schemas"]["ExecutionView"][];
            /** Nextcursor */
            nextCursor: string | null;
        };
        /** ExecutionView */
        ExecutionView: {
            /** Id */
            id: string;
            /** Instrumentid */
            instrumentId: string;
            /** Sourcekey */
            sourceKey: string;
            /**
             * Side
             * @enum {string}
             */
            side: "BUY" | "SELL";
            /** Quantityshares */
            quantityShares: number;
            /** Price */
            price: string;
            /** Grossamount */
            grossAmount: string;
            /** Totalfees */
            totalFees: string;
            fees: components["schemas"]["ActualFees"];
            /** Cashdelta */
            cashDelta: string;
            /** Realizedpnl */
            realizedPnl: string | null;
            /**
             * Executedat
             * Format: date-time
             */
            executedAt: string;
            /**
             * Recordedat
             * Format: date-time
             */
            recordedAt: string;
            /** Source */
            source: string;
            /** Accountversion */
            accountVersion: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
            /** Database */
            database: string;
        };
        /** InstrumentPage */
        InstrumentPage: {
            /** Instruments */
            instruments: components["schemas"]["InstrumentView"][];
            /** Nextcursor */
            nextCursor: string | null;
            universe: components["schemas"]["UniverseView"] | null;
        };
        /** InstrumentView */
        InstrumentView: {
            /** Id */
            id: string;
            /** Code */
            code: string;
            /**
             * Exchange
             * @enum {string}
             */
            exchange: "SH" | "SZ" | "BJ";
            /** Name */
            name: string;
            /**
             * Board
             * @enum {string}
             */
            board: "MAIN" | "STAR" | "CHINEXT" | "BEIJING" | "UNKNOWN";
            /**
             * Firstseenat
             * Format: date-time
             */
            firstSeenAt: string;
            /**
             * Lastseenat
             * Format: date-time
             */
            lastSeenAt: string;
            /** Iscurrent */
            isCurrent: boolean;
            /**
             * Executionsupported
             * @default false
             */
            executionSupported: boolean;
            /**
             * Historystatus
             * @default CURRENT_ONLY
             * @constant
             */
            historyStatus: "CURRENT_ONLY";
        };
        /** JobView */
        JobView: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /**
             * Status
             * @enum {string}
             */
            status: "QUEUED" | "RUNNING" | "SUCCEEDED" | "PARTIAL" | "FAILED" | "CANCELLED" | "EXPIRED";
            /** Stage */
            stage: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
            /** Cancellationrequested */
            cancellationRequested: boolean;
            /** Result */
            result: {
                [key: string]: unknown;
            } | null;
            /** Errorcode */
            errorCode: string | null;
            /** Message */
            message?: string | null;
        };
        /** LoginInput */
        LoginInput: {
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
        };
        /** Meta */
        Meta: {
            /** Requestid */
            requestId?: string;
            /**
             * Asof
             * Format: date-time
             */
            asOf?: string;
            /** Revision */
            revision?: number | null;
        };
        /** PositionPage */
        PositionPage: {
            /** Positions */
            positions: components["schemas"]["PositionView"][];
            /** Nextcursor */
            nextCursor: string | null;
            /** Accountversion */
            accountVersion: number;
            /**
             * Asof
             * Format: date-time
             */
            asOf: string;
        };
        /** PositionView */
        PositionView: {
            /** Instrumentid */
            instrumentId: string;
            /** Name */
            name: string;
            /** Quantityshares */
            quantityShares: number;
            /** Sellableshares */
            sellableShares: number;
            /** Lockedshares */
            lockedShares: number;
            /** Remainingbasis */
            remainingBasis: string;
            /**
             * Costmethod
             * @default FIFO_ACTUAL_FEES
             * @constant
             */
            costMethod: "FIFO_ACTUAL_FEES";
        };
        /** QuoteView */
        QuoteView: {
            /** Instrumentid */
            instrumentId: string;
            /** Name */
            name: string;
            /** Price */
            price: string | null;
            /** Previousclose */
            previousClose: string | null;
            /** Open */
            open: string | null;
            /** High */
            high: string | null;
            /** Low */
            low: string | null;
            /** Changeratio */
            changeRatio: string | null;
            /**
             * Quotedat
             * Format: date-time
             */
            quotedAt: string;
            /**
             * Receivedat
             * Format: date-time
             */
            receivedAt: string;
            /**
             * Source
             * @default 腾讯财经
             * @constant
             */
            source: "腾讯财经";
            /** Sourceurl */
            sourceUrl: string;
            /**
             * Freshness
             * @enum {string}
             */
            freshness: "RECENT" | "STALE";
            /** Missingreason */
            missingReason?: string | null;
            /**
             * Executioneligible
             * @default false
             * @constant
             */
            executionEligible: false;
        };
        /** ReconciliationView */
        ReconciliationView: {
            /** Accountversion */
            accountVersion: number;
            /** Cashbalance */
            cashBalance: string;
            /** Replaycashbalance */
            replayCashBalance: string;
            /** Executioncount */
            executionCount: number;
            /** Openlotcount */
            openLotCount: number;
            /** Discrepancycount */
            discrepancyCount: number;
            /** Discrepancies */
            discrepancies: components["schemas"]["Discrepancy"][];
            /** Matches */
            matches: boolean;
            /**
             * Scope
             * @default INTERNAL_LEDGER
             */
            scope: string;
            /** Checkedat */
            checkedAt?: string;
        };
        /** ResearchCapability */
        ResearchCapability: {
            /** Available */
            available: boolean;
            /** Model */
            model: string;
            /** Reason */
            reason: string | null;
        };
        /** ResearchInput */
        ResearchInput: {
            /** Instrumentid */
            instrumentId: string;
            /** Question */
            question: string;
            /** Evidenceids */
            evidenceIds: string[];
        };
        /** UniverseView */
        UniverseView: {
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** Sourceurl */
            sourceUrl: string;
            /** Count */
            count: number;
            /** Contenthash */
            contentHash: string;
            /**
             * Acquiredat
             * Format: date-time
             */
            acquiredAt: string;
        };
        /** UserView */
        UserView: {
            /** Id */
            id: string;
            /** Username */
            username: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WatchInput */
        WatchInput: {
            /** Instrumentid */
            instrumentId: string;
        };
        /** WatchPage */
        WatchPage: {
            /** Instruments */
            instruments: components["schemas"]["InstrumentView"][];
            /** Nextcursor */
            nextCursor: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    sign_in_api_v1_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_UserView_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_info_api_v1_sessions_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_UserView_"];
                };
            };
        };
    };
    sign_out_api_v1_sessions_current_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_accounts_api_v1_accounts_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_AccountPage_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_account_api_v1_accounts_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_AccountView_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    account_balance_api_v1_accounts__account_id__balance_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_AccountBalance_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cash_history_api_v1_accounts__account_id__cash_flows_get: {
        parameters: {
            query?: {
                cursor?: number | null;
                limit?: number;
            };
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_CashPage_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cash_flow_api_v1_accounts__account_id__cash_flows_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CashFlowInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_CashEntryView_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execution_history_api_v1_accounts__account_id__executions_get: {
        parameters: {
            query?: {
                cursor?: number | null;
                limit?: number;
            };
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ExecutionPage_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_execution_api_v1_accounts__account_id__executions_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecutionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ExecutionView_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    positions_api_v1_accounts__account_id__positions_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_PositionPage_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reconcile_api_v1_accounts__account_id__reconciliation_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ReconciliationView_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_instruments_api_v1_instruments_get: {
        parameters: {
            query?: {
                query?: string;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_InstrumentPage_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_instrument_api_v1_instruments__instrument_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instrument_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_InstrumentView_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quote_api_v1_instruments__instrument_id__quotes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instrument_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_QuoteView_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_watches_api_v1_watchlists_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_WatchPage_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_watch_api_v1_watchlists_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_watch_api_v1_watchlists__instrument_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instrument_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    research_capability_api_v1_research_capability_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ResearchCapability_"];
                };
            };
        };
    };
    create_evidence_api_v1_evidence_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvidenceInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_EvidenceView_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evidence_api_v1_evidence__evidence_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evidence_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_EvidenceView_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_evidence_api_v1_instruments__instrument_id__evidence_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                instrument_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_EvidencePage_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_research_api_v1_instruments__instrument_id__research_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                instrument_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_AssessmentPage_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    research_run_api_v1_research_runs_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResearchInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_JobView_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_JobView_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_v1_jobs__job_id__cancellations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_JobView_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_Health_"];
                };
            };
        };
    };
}
