"""account cash ledger

Revision ID: 0003
Revises: 0002
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment_accounts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('max_position_percent', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('creation_key', sa.String(length=128), nullable=False),
    sa.Column('creation_hash', sa.String(length=64), nullable=False),
    sa.Column('creation_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("currency = 'CNY'", name=op.f('ck_investment_accounts_currency')),
    sa.CheckConstraint("kind IN ('REAL','SIMULATED')", name=op.f('ck_investment_accounts_kind')),
    sa.CheckConstraint('max_position_percent BETWEEN 1 AND 100', name=op.f('ck_investment_accounts_risk_limit')),
    sa.CheckConstraint('version >= 1', name=op.f('ck_investment_accounts_version')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_investment_accounts_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investment_accounts')),
    sa.UniqueConstraint('owner_id', 'creation_key', name=op.f('uq_investment_accounts_owner_id'))
    )
    op.create_index(op.f('ix_investment_accounts_owner_id'), 'investment_accounts', ['owner_id'], unique=False)
    op.create_table('cash_entries',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.String(length=32), nullable=False),
    sa.Column('source_key', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('source', sa.String(length=300), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('account_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("(kind = 'WITHDRAWAL' AND amount < 0) OR (kind IN ('OPENING','DEPOSIT') AND amount > 0)", name=op.f('ck_cash_entries_signed_amount')),
    sa.CheckConstraint("kind IN ('OPENING','DEPOSIT','WITHDRAWAL')", name=op.f('ck_cash_entries_kind')),
    sa.ForeignKeyConstraint(['account_id'], ['investment_accounts.id'], name=op.f('fk_cash_entries_account_id_investment_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_entries')),
    sa.UniqueConstraint('account_id', 'account_version', name='uq_cash_entries_version'),
    sa.UniqueConstraint('account_id', 'source_key', name='uq_cash_entries_source')
    )
    op.create_index(op.f('ix_cash_entries_account_id'), 'cash_entries', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cash_entries_account_id'), table_name='cash_entries')
    op.drop_table('cash_entries')
    op.drop_index(op.f('ix_investment_accounts_owner_id'), table_name='investment_accounts')
    op.drop_table('investment_accounts')
    # ### end Alembic commands ###
