"""market identity snapshots watches

Revision ID: 0004
Revises: 0003
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments',
    sa.Column('id', sa.String(length=9), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('exchange', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('board', sa.String(length=16), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.CheckConstraint("exchange IN ('SH','SZ','BJ')", name=op.f('ck_instruments_exchange')),
    sa.CheckConstraint("id = exchange || '.' || code", name=op.f('ck_instruments_identity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instruments'))
    )
    op.create_index(op.f('ix_instruments_code'), 'instruments', ['code'], unique=False)
    op.create_index(op.f('ix_instruments_name'), 'instruments', ['name'], unique=False)
    op.create_table('universe_snapshots',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('source_url', sa.String(length=300), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('members', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_universe_snapshots'))
    )
    op.create_index(op.f('ix_universe_snapshots_acquired_at'), 'universe_snapshots', ['acquired_at'], unique=False)
    op.create_table('watchlist_members',
    sa.Column('owner_id', sa.String(length=32), nullable=False),
    sa.Column('instrument_id', sa.String(length=9), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_watchlist_members_instrument_id_instruments')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_watchlist_members_owner_id_users')),
    sa.PrimaryKeyConstraint('owner_id', 'instrument_id', name=op.f('pk_watchlist_members'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist_members')
    op.drop_index(op.f('ix_universe_snapshots_acquired_at'), table_name='universe_snapshots')
    op.drop_table('universe_snapshots')
    op.drop_index(op.f('ix_instruments_name'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_code'), table_name='instruments')
    op.drop_table('instruments')
    # ### end Alembic commands ###
