"""evidence and research assessments

Revision ID: 0005
Revises: 0004
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=False),
    sa.Column('instrument_id', sa.String(length=9), nullable=False),
    sa.Column('source_key', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provenance', sa.String(length=30), nullable=False),
    sa.Column('validation', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_evidence_items_instrument_id_instruments')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_evidence_items_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_items')),
    sa.UniqueConstraint('owner_id', 'source_key', name=op.f('uq_evidence_items_owner_id'))
    )
    op.create_index(op.f('ix_evidence_items_instrument_id'), 'evidence_items', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_evidence_items_owner_id'), 'evidence_items', ['owner_id'], unique=False)
    op.create_table('research_assessments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=False),
    sa.Column('instrument_id', sa.String(length=9), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('protocol_version', sa.String(length=80), nullable=False),
    sa.Column('model_id', sa.String(length=120), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('evidence_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_research_assessments_instrument_id_instruments')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_research_assessments_job_id_jobs')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_research_assessments_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_assessments')),
    sa.UniqueConstraint('job_id', name=op.f('uq_research_assessments_job_id'))
    )
    op.create_index(op.f('ix_research_assessments_instrument_id'), 'research_assessments', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_research_assessments_owner_id'), 'research_assessments', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_assessments_owner_id'), table_name='research_assessments')
    op.drop_index(op.f('ix_research_assessments_instrument_id'), table_name='research_assessments')
    op.drop_table('research_assessments')
    op.drop_index(op.f('ix_evidence_items_owner_id'), table_name='evidence_items')
    op.drop_index(op.f('ix_evidence_items_instrument_id'), table_name='evidence_items')
    op.drop_table('evidence_items')
    # ### end Alembic commands ###
