"""custody transfer facts

Revision ID: 08e085a79bba
Revises: 0008_execution_replacement
"""
from alembic import op
import sqlalchemy as sa


revision = '08e085a79bba'
down_revision = '0008_execution_replacement'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custody_transfers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.String(length=32), nullable=False),
    sa.Column('instrument_id', sa.String(length=9), nullable=False),
    sa.Column('quantity_shares', sa.Integer(), nullable=False),
    sa.Column('cost_basis', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('acquired_date', sa.Date(), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_key', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=300), nullable=False),
    sa.Column('command_key', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('account_version', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('cost_basis >= 0', name=op.f('ck_custody_transfers_basis')),
    sa.CheckConstraint('quantity_shares > 0 AND quantity_shares <= 1000000000', name=op.f('ck_custody_transfers_quantity')),
    sa.ForeignKeyConstraint(['account_id'], ['investment_accounts.id'], name=op.f('fk_custody_transfers_account_id_investment_accounts')),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_custody_transfers_instrument_id_instruments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_custody_transfers')),
    sa.UniqueConstraint('account_id', 'account_version', name='uq_transfer_version'),
    sa.UniqueConstraint('account_id', 'command_key', name='uq_transfer_command'),
    sa.UniqueConstraint('account_id', 'source_key', name='uq_transfer_source')
    )
    op.create_index(op.f('ix_custody_transfers_account_id'), 'custody_transfers', ['account_id'], unique=False)
    op.add_column('position_lots', sa.Column('transfer_id', sa.String(length=32), nullable=True))
    op.create_unique_constraint(op.f('uq_position_lots_transfer_id'), 'position_lots', ['transfer_id'])
    op.create_foreign_key(op.f('fk_position_lots_transfer_id_custody_transfers'), 'position_lots', 'custody_transfers', ['transfer_id'], ['id'])
    op.drop_constraint(op.f("ck_position_lots_single_origin"), "position_lots", type_="check")
    op.create_check_constraint(op.f("ck_position_lots_single_origin"), "position_lots",
        "(execution_id IS NOT NULL)::int + (opening_id IS NOT NULL)::int "
        "+ (transfer_id IS NOT NULL)::int = 1")


def downgrade() -> None:
    if op.get_bind().scalar(sa.text("SELECT count(*) FROM custody_transfers")):
        raise RuntimeError("Cannot discard recorded custody facts")
    op.drop_constraint(op.f("ck_position_lots_single_origin"), "position_lots", type_="check")
    op.create_check_constraint(op.f("ck_position_lots_single_origin"), "position_lots",
        "(execution_id IS NOT NULL)::int + (opening_id IS NOT NULL)::int = 1")
    op.drop_constraint(op.f('fk_position_lots_transfer_id_custody_transfers'), 'position_lots', type_='foreignkey')
    op.drop_constraint(op.f('uq_position_lots_transfer_id'), 'position_lots', type_='unique')
    op.drop_column('position_lots', 'transfer_id')
    op.drop_index(op.f('ix_custody_transfers_account_id'), table_name='custody_transfers')
    op.drop_table('custody_transfers')
    # ### end Alembic commands ###
