"""actual dividend and withholding cash facts

Revision ID: 0a722e336341
Revises: 8cd8d36e4cf7
"""
from alembic import op
import sqlalchemy as sa


revision = '0a722e336341'
down_revision = '8cd8d36e4cf7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cash_entries', sa.Column('instrument_id', sa.String(length=9), nullable=True))
    op.add_column('cash_entries', sa.Column('corporate_source_key', sa.String(length=128), nullable=True))
    op.create_unique_constraint('uq_cash_corporate_source', 'cash_entries', ['account_id', 'corporate_source_key'])
    op.create_foreign_key(op.f('fk_cash_entries_instrument_id_instruments'), 'cash_entries', 'instruments', ['instrument_id'], ['id'])
    op.drop_constraint(op.f("ck_cash_entries_kind"), "cash_entries", type_="check")
    op.drop_constraint(op.f("ck_cash_entries_signed_amount"), "cash_entries", type_="check")
    op.create_check_constraint(op.f("ck_cash_entries_kind"), "cash_entries",
                               "kind IN ('OPENING','DEPOSIT','WITHDRAWAL','EXECUTION','REVERSAL',"
                               "'CASH_DIVIDEND','DIVIDEND_TAX')")
    op.create_check_constraint(op.f("ck_cash_entries_signed_amount"), "cash_entries",
                               "(kind IN ('WITHDRAWAL','DIVIDEND_TAX') AND amount < 0) OR "
                               "(kind IN ('OPENING','DEPOSIT','CASH_DIVIDEND') AND amount > 0) OR "
                               "kind IN ('EXECUTION','REVERSAL')")
    op.create_check_constraint(op.f("ck_cash_entries_corporate_link"), "cash_entries",
                               "(kind IN ('CASH_DIVIDEND','DIVIDEND_TAX')) = "
                               "(instrument_id IS NOT NULL) AND "
                               "(kind IN ('CASH_DIVIDEND','DIVIDEND_TAX')) = "
                               "(corporate_source_key IS NOT NULL)")
    # ### end Alembic commands ###


def downgrade() -> None:
    if op.get_bind().scalar(sa.text(
        "SELECT count(*) FROM cash_entries WHERE kind IN ('CASH_DIVIDEND','DIVIDEND_TAX')"
    )):
        raise RuntimeError("存在公司行动现金事实，禁止降级丢失账本")
    op.drop_constraint(op.f("ck_cash_entries_corporate_link"), "cash_entries", type_="check")
    op.drop_constraint(op.f("ck_cash_entries_kind"), "cash_entries", type_="check")
    op.drop_constraint(op.f("ck_cash_entries_signed_amount"), "cash_entries", type_="check")
    op.create_check_constraint(op.f("ck_cash_entries_kind"), "cash_entries",
                               "kind IN ('OPENING','DEPOSIT','WITHDRAWAL','EXECUTION','REVERSAL')")
    op.create_check_constraint(op.f("ck_cash_entries_signed_amount"), "cash_entries",
                               "(kind = 'WITHDRAWAL' AND amount < 0) OR "
                               "(kind IN ('OPENING','DEPOSIT') AND amount > 0) OR "
                               "kind IN ('EXECUTION','REVERSAL')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_cash_entries_instrument_id_instruments'), 'cash_entries', type_='foreignkey')
    op.drop_constraint('uq_cash_corporate_source', 'cash_entries', type_='unique')
    op.drop_column('cash_entries', 'corporate_source_key')
    op.drop_column('cash_entries', 'instrument_id')
    # ### end Alembic commands ###
