"""execution_command_receipts

Revision ID: 1f9cc1be43e0
Revises: cceb6410ca50
"""
from alembic import op
import sqlalchemy as sa


revision = '1f9cc1be43e0'
down_revision = 'cceb6410ca50'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_commands',
    sa.Column('account_id', sa.String(length=32), nullable=False),
    sa.Column('command_key', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('execution_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['investment_accounts.id'], name=op.f('fk_execution_commands_account_id_investment_accounts')),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], name=op.f('fk_execution_commands_execution_id_executions')),
    sa.PrimaryKeyConstraint('account_id', 'command_key', name=op.f('pk_execution_commands'))
    )
    op.execute("INSERT INTO execution_commands (account_id, command_key, request_hash, execution_id) "
               "SELECT account_id, command_key, request_hash, id FROM executions")
    # ### end Alembic commands ###


def downgrade() -> None:
    if op.get_bind().scalar(sa.text("SELECT count(*) FROM execution_commands")):
        raise RuntimeError("存在成交幂等回执，禁止删除后回退")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('execution_commands')
    # ### end Alembic commands ###
