"""manual plans reservations and version events

Revision ID: 663f3b4aacad
Revises: 9f1baf03940c
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '663f3b4aacad'
down_revision = '9f1baf03940c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_plans',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.String(length=32), nullable=False),
    sa.Column('instrument_id', sa.String(length=9), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('quantity_shares', sa.Integer(), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('fee_budget', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('recorded_shares', sa.Integer(), nullable=False),
    sa.Column('reserved_cash', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('reserved_shares', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("side IN ('BUY','SELL')", name=op.f('ck_execution_plans_side')),
    sa.CheckConstraint("status IN ('CONFIRMED','PARTIALLY_RECORDED','COMPLETED','CANCELLED','EXPIRED','INVALIDATED')", name=op.f('ck_execution_plans_status')),
    sa.CheckConstraint('quantity_shares > 0 AND recorded_shares >= 0', name=op.f('ck_execution_plans_quantity')),
    sa.CheckConstraint('reserved_cash >= 0 AND reserved_shares >= 0', name=op.f('ck_execution_plans_reservation')),
    sa.ForeignKeyConstraint(['account_id'], ['investment_accounts.id'], name=op.f('fk_execution_plans_account_id_investment_accounts')),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_execution_plans_instrument_id_instruments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_plans'))
    )
    op.create_index(op.f('ix_execution_plans_account_id'), 'execution_plans', ['account_id'], unique=False)
    op.create_table('plan_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.String(length=32), nullable=False),
    sa.Column('plan_id', sa.String(length=32), nullable=False),
    sa.Column('account_version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('command_key', sa.String(length=256), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['investment_accounts.id'], name=op.f('fk_plan_events_account_id_investment_accounts')),
    sa.ForeignKeyConstraint(['plan_id'], ['execution_plans.id'], name=op.f('fk_plan_events_plan_id_execution_plans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_events')),
    sa.UniqueConstraint('account_id', 'command_key', name='uq_plan_events_command'),
    sa.UniqueConstraint('plan_id', 'revision', name='uq_plan_events_revision')
    )
    op.create_index(op.f('ix_plan_events_account_id'), 'plan_events', ['account_id'], unique=False)
    op.create_index(op.f('ix_plan_events_plan_id'), 'plan_events', ['plan_id'], unique=False)
    op.add_column('executions', sa.Column('plan_id', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_executions_plan_id'), 'executions', ['plan_id'], unique=False)
    op.create_foreign_key(op.f('fk_executions_plan_id_execution_plans'), 'executions', 'execution_plans', ['plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    if op.get_bind().scalar(sa.text("SELECT count(*) FROM execution_plans")):
        raise RuntimeError("已有计划与预留审计，禁止删除后回退")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_executions_plan_id_execution_plans'), 'executions', type_='foreignkey')
    op.drop_index(op.f('ix_executions_plan_id'), table_name='executions')
    op.drop_column('executions', 'plan_id')
    op.drop_index(op.f('ix_plan_events_plan_id'), table_name='plan_events')
    op.drop_index(op.f('ix_plan_events_account_id'), table_name='plan_events')
    op.drop_table('plan_events')
    op.drop_index(op.f('ix_execution_plans_account_id'), table_name='execution_plans')
    op.drop_table('execution_plans')
    # ### end Alembic commands ###
