"""opening custody facts and explicit lot origin

Revision ID: 8cd8d36e4cf7
Revises: 0006_lot_identity
"""
from alembic import op
import sqlalchemy as sa


revision = '8cd8d36e4cf7'
down_revision = '0006_lot_identity'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opening_lots',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.String(length=32), nullable=False),
    sa.Column('instrument_id', sa.String(length=9), nullable=False),
    sa.Column('quantity_shares', sa.Integer(), nullable=False),
    sa.Column('cost_basis', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('acquired_date', sa.Date(), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_key', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=300), nullable=False),
    sa.Column('command_key', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('account_version', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('cost_basis >= 0', name=op.f('ck_opening_lots_basis')),
    sa.CheckConstraint('quantity_shares > 0 AND quantity_shares <= 1000000000', name=op.f('ck_opening_lots_quantity')),
    sa.ForeignKeyConstraint(['account_id'], ['investment_accounts.id'], name=op.f('fk_opening_lots_account_id_investment_accounts')),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_opening_lots_instrument_id_instruments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opening_lots')),
    sa.UniqueConstraint('account_id', 'account_version', name='uq_opening_version'),
    sa.UniqueConstraint('account_id', 'command_key', name='uq_opening_command'),
    sa.UniqueConstraint('account_id', 'source_key', name='uq_opening_source')
    )
    op.create_index(op.f('ix_opening_lots_account_id'), 'opening_lots', ['account_id'], unique=False)
    op.add_column('position_lots', sa.Column('opening_id', sa.String(length=32), nullable=True))
    op.create_unique_constraint(op.f('uq_position_lots_opening_id'), 'position_lots', ['opening_id'])
    op.create_foreign_key(op.f('fk_position_lots_opening_id_opening_lots'), 'position_lots', 'opening_lots', ['opening_id'], ['id'])
    op.create_check_constraint("ck_position_lots_single_origin", "position_lots",
                               "(execution_id IS NOT NULL)::int + (opening_id IS NOT NULL)::int = 1")
    # ### end Alembic commands ###


def downgrade() -> None:
    if op.get_bind().scalar(sa.text("SELECT count(*) FROM opening_lots")):
        raise RuntimeError("存在期初持仓事实，禁止删除后降级")
    op.drop_constraint("ck_position_lots_single_origin", "position_lots", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_position_lots_opening_id_opening_lots'), 'position_lots', type_='foreignkey')
    op.drop_constraint(op.f('uq_position_lots_opening_id'), 'position_lots', type_='unique')
    op.drop_column('position_lots', 'opening_id')
    op.drop_index(op.f('ix_opening_lots_account_id'), table_name='opening_lots')
    op.drop_table('opening_lots')
    # ### end Alembic commands ###
