"""persist bounded execution import previews

Revision ID: 9f1baf03940c
Revises: d3d6d6e07b60
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '9f1baf03940c'
down_revision = 'd3d6d6e07b60'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_imports',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.String(length=32), nullable=False),
    sa.Column('account_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('command_key', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('facts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rows', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('creation_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('committed_version', sa.Integer(), nullable=True),
    sa.CheckConstraint("status IN ('READY','REJECTED','COMMITTED')", name=op.f('ck_execution_imports_status')),
    sa.ForeignKeyConstraint(['account_id'], ['investment_accounts.id'], name=op.f('fk_execution_imports_account_id_investment_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_imports')),
    sa.UniqueConstraint('account_id', 'command_key', name='uq_execution_imports_command')
    )
    op.create_index(op.f('ix_execution_imports_account_id'), 'execution_imports', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    if op.get_bind().scalar(sa.text("SELECT count(*) FROM execution_imports")):
        raise RuntimeError("存在导入预览或审计记录，禁止删除后回退")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_imports_account_id'), table_name='execution_imports')
    op.drop_table('execution_imports')
    # ### end Alembic commands ###
