"""execution_facts_and_lots

Revision ID: cceb6410ca50
Revises: 0005
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'cceb6410ca50'
down_revision = '0005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('executions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.String(length=32), nullable=False),
    sa.Column('instrument_id', sa.String(length=9), nullable=False),
    sa.Column('source_key', sa.String(length=128), nullable=False),
    sa.Column('command_key', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('fact_hash', sa.String(length=64), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('quantity_shares', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('total_fees', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('fees', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cash_delta', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=300), nullable=False),
    sa.Column('account_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("side IN ('BUY','SELL')", name=op.f('ck_executions_side')),
    sa.CheckConstraint('price > 0 AND gross_amount > 0 AND total_fees >= 0', name=op.f('ck_executions_amounts')),
    sa.CheckConstraint('quantity_shares > 0 AND quantity_shares <= 1000000000', name=op.f('ck_executions_quantity')),
    sa.ForeignKeyConstraint(['account_id'], ['investment_accounts.id'], name=op.f('fk_executions_account_id_investment_accounts')),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_executions_instrument_id_instruments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_executions')),
    sa.UniqueConstraint('account_id', 'account_version', name='uq_executions_version'),
    sa.UniqueConstraint('account_id', 'command_key', name='uq_executions_command'),
    sa.UniqueConstraint('account_id', 'source_key', name='uq_executions_source')
    )
    op.create_index(op.f('ix_executions_account_id'), 'executions', ['account_id'], unique=False)
    op.create_index(op.f('ix_executions_instrument_id'), 'executions', ['instrument_id'], unique=False)
    op.create_table('lot_consumptions',
    sa.Column('sell_execution_id', sa.String(length=32), nullable=False),
    sa.Column('buy_execution_id', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('basis', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.CheckConstraint('quantity > 0 AND basis >= 0', name=op.f('ck_lot_consumptions_amounts')),
    sa.ForeignKeyConstraint(['buy_execution_id'], ['executions.id'], name=op.f('fk_lot_consumptions_buy_execution_id_executions')),
    sa.ForeignKeyConstraint(['sell_execution_id'], ['executions.id'], name=op.f('fk_lot_consumptions_sell_execution_id_executions')),
    sa.PrimaryKeyConstraint('sell_execution_id', 'buy_execution_id', name=op.f('pk_lot_consumptions'))
    )
    op.create_table('position_lots',
    sa.Column('execution_id', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.String(length=32), nullable=False),
    sa.Column('instrument_id', sa.String(length=9), nullable=False),
    sa.Column('acquired_date', sa.Date(), nullable=False),
    sa.Column('remaining_quantity', sa.Integer(), nullable=False),
    sa.Column('remaining_basis', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.CheckConstraint('remaining_basis >= 0', name=op.f('ck_position_lots_basis')),
    sa.CheckConstraint('remaining_quantity > 0 OR remaining_basis = 0', name=op.f('ck_position_lots_closed_basis')),
    sa.CheckConstraint('remaining_quantity >= 0', name=op.f('ck_position_lots_quantity')),
    sa.ForeignKeyConstraint(['account_id'], ['investment_accounts.id'], name=op.f('fk_position_lots_account_id_investment_accounts')),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], name=op.f('fk_position_lots_execution_id_executions')),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_position_lots_instrument_id_instruments')),
    sa.PrimaryKeyConstraint('execution_id', name=op.f('pk_position_lots'))
    )
    op.create_index(op.f('ix_position_lots_account_id'), 'position_lots', ['account_id'], unique=False)
    op.create_index(op.f('ix_position_lots_instrument_id'), 'position_lots', ['instrument_id'], unique=False)
    op.add_column('cash_entries', sa.Column('execution_id', sa.String(length=32), nullable=True))
    op.create_unique_constraint(op.f('uq_cash_entries_execution_id'), 'cash_entries', ['execution_id'])
    op.create_foreign_key(op.f('fk_cash_entries_execution_id_executions'), 'cash_entries', 'executions', ['execution_id'], ['id'])
    op.drop_constraint('uq_cash_entries_source', 'cash_entries', type_='unique')
    op.create_unique_constraint('uq_cash_entries_source', 'cash_entries', ['account_id', 'kind', 'source_key'])
    op.drop_constraint(op.f('ck_cash_entries_kind'), 'cash_entries', type_='check')
    op.drop_constraint(op.f('ck_cash_entries_signed_amount'), 'cash_entries', type_='check')
    op.create_check_constraint(op.f('ck_cash_entries_kind'), 'cash_entries',
                               "kind IN ('OPENING','DEPOSIT','WITHDRAWAL','EXECUTION')")
    op.create_check_constraint(op.f('ck_cash_entries_signed_amount'), 'cash_entries',
                               "(kind = 'WITHDRAWAL' AND amount < 0) OR "
                               "(kind IN ('OPENING','DEPOSIT') AND amount > 0) OR kind = 'EXECUTION'")
    op.create_check_constraint(op.f('ck_cash_entries_execution_link'), 'cash_entries',
                               "(kind = 'EXECUTION') = (execution_id IS NOT NULL)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # Do not discard financial facts to force a downgrade.
    if op.get_bind().scalar(sa.text("SELECT count(*) FROM executions")):
        raise RuntimeError("成交事实存在，禁止回退至不支持成交的账本")
    op.drop_constraint(op.f('ck_cash_entries_execution_link'), 'cash_entries', type_='check')
    op.drop_constraint(op.f('ck_cash_entries_kind'), 'cash_entries', type_='check')
    op.drop_constraint(op.f('ck_cash_entries_signed_amount'), 'cash_entries', type_='check')
    op.create_check_constraint(op.f('ck_cash_entries_kind'), 'cash_entries',
                               "kind IN ('OPENING','DEPOSIT','WITHDRAWAL')")
    op.create_check_constraint(op.f('ck_cash_entries_signed_amount'), 'cash_entries',
                               "(kind = 'WITHDRAWAL' AND amount < 0) OR "
                               "(kind IN ('OPENING','DEPOSIT') AND amount > 0)")
    op.drop_constraint('uq_cash_entries_source', 'cash_entries', type_='unique')
    op.create_unique_constraint('uq_cash_entries_source', 'cash_entries', ['account_id', 'source_key'])
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_cash_entries_execution_id_executions'), 'cash_entries', type_='foreignkey')
    op.drop_constraint(op.f('uq_cash_entries_execution_id'), 'cash_entries', type_='unique')
    op.drop_column('cash_entries', 'execution_id')
    op.drop_index(op.f('ix_position_lots_instrument_id'), table_name='position_lots')
    op.drop_index(op.f('ix_position_lots_account_id'), table_name='position_lots')
    op.drop_table('position_lots')
    op.drop_table('lot_consumptions')
    op.drop_index(op.f('ix_executions_instrument_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_account_id'), table_name='executions')
    op.drop_table('executions')
    # ### end Alembic commands ###
