"""immutable execution reversals and command receipts

Revision ID: d3d6d6e07b60
Revises: 1f9cc1be43e0
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'd3d6d6e07b60'
down_revision = '1f9cc1be43e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_corrections',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.String(length=32), nullable=False),
    sa.Column('execution_id', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('command_key', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('account_version', sa.Integer(), nullable=False),
    sa.Column('reversal_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['investment_accounts.id'], name=op.f('fk_execution_corrections_account_id_investment_accounts')),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_execution_corrections_actor_id_users')),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], name=op.f('fk_execution_corrections_execution_id_executions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_corrections')),
    sa.UniqueConstraint('account_id', 'account_version', name='uq_corrections_version'),
    sa.UniqueConstraint('account_id', 'command_key', name='uq_corrections_command'),
    sa.UniqueConstraint('execution_id', name=op.f('uq_execution_corrections_execution_id'))
    )
    op.create_index(op.f('ix_execution_corrections_account_id'), 'execution_corrections', ['account_id'], unique=False)
    op.add_column('cash_entries', sa.Column('correction_id', sa.String(length=32), nullable=True))
    op.create_unique_constraint(op.f('uq_cash_entries_correction_id'), 'cash_entries', ['correction_id'])
    op.create_foreign_key(op.f('fk_cash_entries_correction_id_execution_corrections'), 'cash_entries', 'execution_corrections', ['correction_id'], ['id'])
    op.add_column('execution_commands', sa.Column('result', postgresql.JSONB(), nullable=False, server_default='{}'))
    # Freeze existing command responses before any correction can recalculate derived PnL.
    op.execute("""
        UPDATE execution_commands c SET result =
        (to_jsonb(e) - 'command_key' - 'request_hash' - 'fact_hash' - 'account_id')
        || jsonb_build_object('price', e.price::text, 'gross_amount', e.gross_amount::text,
            'total_fees', e.total_fees::text, 'cash_delta', e.cash_delta::text,
            'realized_pnl', CASE WHEN e.realized_pnl IS NULL THEN NULL ELSE e.realized_pnl::text END)
        FROM executions e WHERE e.id = c.execution_id
    """)
    op.alter_column('execution_commands', 'result', server_default=None)
    op.drop_constraint(op.f('ck_cash_entries_kind'), 'cash_entries', type_='check')
    op.drop_constraint(op.f('ck_cash_entries_signed_amount'), 'cash_entries', type_='check')
    op.create_check_constraint(op.f('ck_cash_entries_kind'), 'cash_entries',
        "kind IN ('OPENING','DEPOSIT','WITHDRAWAL','EXECUTION','REVERSAL')")
    op.create_check_constraint(op.f('ck_cash_entries_signed_amount'), 'cash_entries',
        "(kind = 'WITHDRAWAL' AND amount < 0) OR "
        "(kind IN ('OPENING','DEPOSIT') AND amount > 0) OR kind IN ('EXECUTION','REVERSAL')")
    op.create_check_constraint(op.f('ck_cash_entries_correction_link'), 'cash_entries',
        "(kind = 'REVERSAL') = (correction_id IS NOT NULL)")
    # ### end Alembic commands ###


def downgrade() -> None:
    if op.get_bind().scalar(sa.text("SELECT count(*) FROM execution_corrections")):
        raise RuntimeError("已有冲正事实，禁止删除审计后回退")
    op.drop_constraint(op.f('ck_cash_entries_correction_link'), 'cash_entries', type_='check')
    op.drop_constraint(op.f('ck_cash_entries_kind'), 'cash_entries', type_='check')
    op.drop_constraint(op.f('ck_cash_entries_signed_amount'), 'cash_entries', type_='check')
    op.create_check_constraint(op.f('ck_cash_entries_kind'), 'cash_entries',
        "kind IN ('OPENING','DEPOSIT','WITHDRAWAL','EXECUTION')")
    op.create_check_constraint(op.f('ck_cash_entries_signed_amount'), 'cash_entries',
        "(kind = 'WITHDRAWAL' AND amount < 0) OR "
        "(kind IN ('OPENING','DEPOSIT') AND amount > 0) OR kind = 'EXECUTION'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('execution_commands', 'result')
    op.drop_constraint(op.f('fk_cash_entries_correction_id_execution_corrections'), 'cash_entries', type_='foreignkey')
    op.drop_constraint(op.f('uq_cash_entries_correction_id'), 'cash_entries', type_='unique')
    op.drop_column('cash_entries', 'correction_id')
    op.drop_index(op.f('ix_execution_corrections_account_id'), table_name='execution_corrections')
    op.drop_table('execution_corrections')
    # ### end Alembic commands ###
